### ISSUE TITLE
Sequelize instrumentation doesn't seems to work.

### ISSUE THREAD

**Issue by MollardMichael** [aspecto-io/opentelemetry-ext-js#110]
I have been using pg instrumentation for a while and wanted to see what I could get out of sequelize instrumentation but when I used it, I got no new traces.

Am I missing something ?
Sequelize v5, opentelemetry v 0.19

**Comment by nirsky** [comment]
Hey @MollardMichael!

I just tested it on my setup and it seems to be working fine.
Can you provide some more context so I can try to reproduce it (a repo reproducing the issue will be best)?

Specifically looking for:
- exact instrumentation version
- exact Sequelize version
- Sequelize init snippet
- OpenTelemetry init snippet (including how you configure the instrumentation)
- Sequelize usage

Thanks.

**Comment by MollardMichael** [comment]
Hello @nirsky 

Thank you for your time looking at my request.
I found the issue on my end. I could instrument it alright.
