### ISSUE TITLE
Sequelize and TypeORM should have "suppressInternalInstrumentation" option

### ISSUE THREAD

**Issue by nirsky** [aspecto-io/opentelemetry-ext-js#111]
Those instrumentations always have an underlying operation.  
For example, if using postgres and having [@opentelemetry/instrumentation-pg](https://www.npmjs.com/package/@opentelemetry/instrumentation-pg) installed, we will end up with at least 2 spans for each operation.

Similar use case like:
- AWS creating underlying HTTP span
- Mongoose creating underlying MongoDB span

**Comment by nirsky** [comment]
Added to sequelize as part of https://github.com/aspecto-io/opentelemetry-ext-js/pull/132

**Comment by mottibec** [comment]
Added to typeorm as part of #131
