### ISSUE TITLE
Deprecate old "plugin" packages on NPM

### ISSUE THREAD

**Issue by willarmiros** [aspecto-io/opentelemetry-ext-js#116]
It appears all packages in this repo have been renamed from `opentelemetry-plugin-XXXX` to `opentelemetry-instrumentation-XXXX` in line with the upstream's change in terminology. It would be nice if the old `plugin` packages could be deprecated in NPM in favor of their `instrumentation` counterparts, since it doesn't look like they'll be maintained anymore. See the old [HTTP plugin package](https://www.npmjs.com/package/@opentelemetry/plugin-http) for reference.

**Comment by blumamir** [comment]
done, thanks
