### ISSUE TITLE
Request to instrument `ws` (websocket) library.

### ISSUE THREAD

**Issue by minho-comcom-ai** [aspecto-io/opentelemetry-ext-js#126]

**Comment by blumamir** [comment]
Hi @minho-comcom-ai 
This package is not currently on our roadmap.

What we can offer, if you choose to write the instrumentation yourself, is to escort you in the development, and review the PR once ready. 
If you choose to host it in this repo, we'll help maintain it and give future support

**Comment by mottibec** [comment]
Hey @minho-comcom-ai 
It sounds like you already use WS, but if you ever decide to switch to socket.io or use it in the future, we just released awesome instrumentation for it!
[Check it out](https://github.com/aspecto-io/opentelemetry-ext-js/tree/master/packages/instrumentation-socket.io)
