### ISSUE TITLE
AMQP instrumentation throws unexpected exception on consumer cancel

### ISSUE THREAD

**Issue by neoeinstein** [aspecto-io/opentelemetry-ext-js#175]
When a consumer is summarily cancelled (perhaps due to a queue being deleted while a consumer is actively consuming messages), `amqplib` sends the consumer a `null` message to indicate that the queue has been cancelled. This is acknowledged by the type of the `message` parameter in the callback. Nonetheless, the code immediately assumes that it cannot be `null` by accessing `.properties`. In the event of a cancellation, this results in a `TypeError` from the instrumentation code. `?.` as on L261 should be used instead before passing the `null` message on to the consumer.

https://github.com/aspecto-io/opentelemetry-ext-js/blob/master/packages/instrumentation-amqplib/src/amqplib.ts#L258-L261

For additional reference, see: https://github.com/squaremo/amqp.node/blob/1b327eba45df6f417e598715aa9010f76407fc29/CHANGELOG.md#breaking-changes

**Comment by blumamir** [comment]
Thanks for reporting this issue and investigating the cause.
I created PR with a fix, feel free to review the changes
