### ISSUE TITLE
AMQP instrumentation exposing credentials in URL

### ISSUE THREAD

**Issue by petrzjunior** [aspecto-io/opentelemetry-ext-js#186]
When connecting to AMQP via URL, the whole URL gets sent in span attributes, potentially exposing username and password. Is it possible to censor it or to exclude the field?

https://github.com/aspecto-io/opentelemetry-ext-js/blob/a58547a574f16b8c7ecb0df01a9b60be39ce3daa/packages/instrumentation-amqplib/src/utils.ts#L89

Example result:

![screenshot](https://user-images.githubusercontent.com/7000918/136922316-10e1e1af-16a0-4bae-ad5a-8df640d79286.png)

**Comment by YanivD** [comment]
IMO parsing the URL ia the best way to solve it.
You can drop the authorization part or replace it with asterisks
