### ISSUE TITLE
Can't get typeorm & kafkajs instrumentation to work

### ISSUE THREAD

**Issue by royi-frontegg** [aspecto-io/opentelemetry-ext-js#190]
Hi,  
I'm not sure what I'm doing wrong and I couldn't find any extra doc
I can't get the typeorm or kafkajs instrumentation to work. I running with NestJS and kafkajs wrapping is implemented in another lib I created.
When running only the official mysql2 instrumentation It is working and showing the queries.
The documentation states that I need to disable internal plugin, but `NodeTracerProvider` configuration does not contain such a member named `plugin`
I would really much appreciate your help!
This is my setup: 

```
import { JaegerExporter } from '@opentelemetry/exporter-jaeger';
import { registerInstrumentations } from '@opentelemetry/instrumentation';
import { ExpressInstrumentation } from '@opentelemetry/instrumentation-express';
import { HttpInstrumentation } from '@opentelemetry/instrumentation-http';
import { IORedisInstrumentation } from '@opentelemetry/instrumentation-ioredis';
import { NestInstrumentation } from '@opentelemetry/instrumentation-nestjs-core';
import { B3Propagator } from '@opentelemetry/propagator-b3';
import { Resource } from '@opentelemetry/resources';
import { SimpleSpanProcessor } from '@opentelemetry/sdk-trace-base';
import { NodeTracerProvider } from '@opentelemetry/sdk-trace-node';
import { SemanticResourceAttributes } from '@opentelemetry/semantic-conventions';
import { KafkaJsInstrumentation } from 'opentelemetry-instrumentation-kafkajs';
import { TypeormInstrumentation } from 'opentelemetry-instrumentation-typeorm';

const provider = new NodeTracerProvider({
  resource: new Resource({
	  [SemanticResourceAttributes.SERVICE_NAME]: 'my-service',
  }),
});
const exporter = new JaegerExporter();
provider.addSpanProcessor(new SimpleSpanProcessor(exporter));

provider.register({propagator: new B3Propagator()});
registerInstrumentations({
  instrumentations: [
	  new ExpressInstrumentation(),
	  new HttpInstrumentation(),
	  // new MySQL2Instrumentation(), <--- working
	  new IORedisInstrumentation(),
	  new KafkaJsInstrumentation(), <--- not working
	  new NestInstrumentation(), <--- not working
	  new TypeormInstrumentation() <--- not working
  ]
});
```

**Comment by blumamir** [comment]
Hi @royi-frontegg , were you able to fix the problem?
is this issue still relevant?

**Comment by royi-frontegg** [comment]
@blumamir Hi,
yes. Still happening in 0.26.0

**Comment by royi-frontegg** [comment]
@blumamir Is it possible that I need to register all data before I start my NestJS application (and as a result also all Kafka + typeorm initializations?)

**Comment by blumamir** [comment]
@royi-frontegg 
You need to register the instrumentations before you (or third party package you are using) "require" any of the instrumented packages.
JS SDK has some warning printed to the diag logger if you try to register an instrumentation that has already been required. 

Can you share how you initialize your application? is the otel setup the first thing that is happening in the application?

**Comment by royi-frontegg** [comment]
@blumamir I think I found the issue. The endpoint should be `https://host:14268/api/traces`. It was left empty for "default"....

**Comment by blumamir** [comment]
Great to hear. These exporter settings can be tricky to get right
