### ISSUE TITLE
fix typescript error in instrumentation-aws-sdk

### ISSUE THREAD

**Issue by taliasegev** [aspecto-io/opentelemetry-ext-js#192]
Fix the following issue - 
`opentelemetry-instrumentation-aws-sdk/dist/src/types.d.ts:3:13 - error TS1192: Module '"/node_modules/aws-sdk/index"' has no default export.

3 import type AWS from 'aws-sdk';
              ~~~


Found 1 error.`

the solution - 
`import type { SQS } from 'aws-sdk';
...
...
export interface AwsSdkSqsProcessCustomAttributeFunction {
    (span: Span, message: SQS.Message): void;
}
`

https://github.com/aspecto-io/opentelemetry-ext-js/pull/194

**Comment by blumamir** [comment]
Thanks again for reporting this issue and working on a fix.
As discussed in the PR, the instrumentation has moved to contrib repo where the issue has been fixed already.
The package is marked as deprecated in this repo.
