### ISSUE TITLE
Make instrumentations compatible with SDK 1.2.0/0.28.0

### ISSUE THREAD

**Issue by FelipeEmerim** [aspecto-io/opentelemetry-ext-js#220]
Opentelemetry released a new version of the base instrumentation and SDK. I would like to help but I know very little about how these packages work. Instead, I will leave the PR from the contrib packages as a reference:

https://github.com/open-telemetry/opentelemetry-js-contrib/pull/984

Here are the changelogs for the new releases:

https://github.com/open-telemetry/opentelemetry-js/releases/tag/v0.28.0
https://github.com/open-telemetry/opentelemetry-js/releases/tag/v1.2.0

**Comment by blumamir** [comment]
Thanks @FelipeEmerim for the notice.
contrib PRs are not yet approved and merged, as there are a couple of issues being fixed currently: 
https://github.com/open-telemetry/opentelemetry-js/pull/2931

I also opened an issue to discuss how versions should be set in instrumentation here:
https://github.com/open-telemetry/opentelemetry-js-contrib/issues/986

I plan to wait for these topics to reach consensus and then apply the version bump in this repo as well. We would be very happy to get your help by contributing a PR with the relevant fixes.
