### ISSUE TITLE
Support MongoDB insert instrumentation for Mongoose

### ISSUE THREAD

**Issue by ds-albans** [aspecto-io/opentelemetry-ext-js#245]
We are currently using both mongoose and mongo instrumentation libraries. When creating documents, we see the instrumentation call for `mongodb.insert` but no instrumentation from `mongoose` for this. For other operations like find, update, we do see both spans.

I believe the likely cause is here: https://github.com/aspecto-io/opentelemetry-ext-js/blob/master/packages/instrumentation-mongoose/src/mongoose.ts#L14

**Comment by blumamir** [comment]
Thanks for reporting this and sorry for the late response.
The instrumentation has moved to the contrib repo [here](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/instrumentation-mongoose).

If the issue is still relevant, please open it in the new repo.
