### ISSUE TITLE
Upgrade OpenTelemetry to use the latest packages which include Metrics v1 GA

### ISSUE THREAD

**Issue by weyert** [aspecto-io/opentelemetry-ext-js#247]
Earlier this week the OpenTelemetry Javascript maintainers have released a new version of `otel-js` which included the major release of Metrics v1 and I was wondering if the dependencies could be updated so it uses the latest versions, such as `@opentelemetry/api`. In the latest version of this package the maintainers merged `@opentelemetry/metrics-api` package

**Comment by blumamir** [comment]
fixed in #248
