### ISSUE TITLE
migration to new instrumentation class

### ISSUE THREAD

**Issue by vmarchaud** [aspecto-io/opentelemetry-ext-js#36]
I'm reaching out because you guys already wrote few instrumentation package for nodejs and i believe it's best to let you know that we implement a new base class called `Instrumentation`.

You can find our tracking issue here: https://github.com/open-telemetry/opentelemetry-js/issues/1074 
I'm in the process of migrating the http/https plugin (i'll ping here with the PR once its done), there is already the `graphql` plugin that have implemented: https://github.com/open-telemetry/opentelemetry-js-contrib/blob/master/plugins/node/opentelemetry-instrumentation-graphql/src/graphql.ts.

There was no discussion yet about removing the old `plugin` mechanism as they still a lot of plugin to migrate but i will try to keep you updated on that

**Comment by vmarchaud** [comment]
PR for the http(s) plugin is here: https://github.com/open-telemetry/opentelemetry-js/pull/1671

**Comment by nirsky** [comment]
Hey @vmarchaud, thanks for the heads up.
We're working on the required adjustments.

**Comment by nirsky** [comment]
New packages committed in PR https://github.com/aspecto-io/opentelemetry-ext-js/pull/61 and released to npm.
