### ISSUE TITLE
Help with lightstep-opentelemetry-launcher-node and aws-sdk

### ISSUE THREAD

**Issue by ErnestChiu2023** [aspecto-io/opentelemetry-ext-js#42]
## Problem tracing SQS message using opentelemetry-launcher-node package
I was trying to setup a simple trace that utilizes a SQS queue hoping that the trace would go through the sender and the receiver. However, the trace appears to be breaking upon receiving the message in the queue. The code that I used can be found [here](https://github.com/ErnestChiu2023/openTelemetrySQSexample). 

I was hoping the following operations would fall all under a single trace.

![image](https://user-images.githubusercontent.com/39243004/101822995-058a4d80-3adf-11eb-99e6-e3eaa93ef9a3.png)
![image](https://user-images.githubusercontent.com/39243004/101822743-aaf0f180-3ade-11eb-8d99-ef73bbead7db.png)

Can you please explain what I'm doing wrong and what am I missing? Or if this is even possible as I'm still new to open telemetry.  

Any help is appreciated, Thanks! 😄

**Comment by blumamir** [comment]
Hi @ErnestChiu2023 ,
The SQS implementation is following the [Batch receiving for Messaging systems](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/messaging.md#batch-receiving) part of the specification. 
It can be a bit confusing. There is a single SQS `receive` operation, followed by multiple per-message `process` operations, each of which with a possible different traceId and spanId. 
It doesn't make sense to choose one arbitrary message out of the (possibly) 10, and set it as the parent span for the receive operation. Therefore, the source spanId and traceId are being populated as a [Link](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#specifying-links) on the processing span.

**Comment by blumamir** [comment]
Closing the issue since the plugin follows the spec.
Feel free to reach out if you have any other questions.
