### ISSUE TITLE
Opentelemetry version 0.15 support

### ISSUE THREAD

**Issue by sidharthv96** [aspecto-io/opentelemetry-ext-js#54]
As `withSpan` was removed, the plugin will not work anymore.

https://github.com/open-telemetry/opentelemetry-js/pull/1764#pullrequestreview-555605702

Please mention in Readme to use version 0.14 till a fix is released.

**Comment by blumamir** [comment]
Hi @sidharthv96
Since the plugins depend on `@opentelemetry/api@^0.14.0`, they should install v0.14.0 along with any other api versions and use it (and not v0.15.0).
Did you try it with v0.15.0 and had a compatibility issue? if so can you elaborate on what you observed?

Anyhow, we plan to migrate to v0.15.0 in the next week or so.

**Comment by sidharthv96** [comment]
Yes, I'm pretty new to the OpenTelemetry Ecosystem and was following tutorials which only had `npm install <package-name>` so that installed v0.15 and when I later installed this plugin, it threw the error that this._tracer.withSpan is not a function. 

The express plugin also had similar issue. I was able to find the root cause after some digging around the release notes and source code.

https://github.com/open-telemetry/opentelemetry-js/pull/1764#pullrequestreview-555605702 mentions how we should replace the usage of withSpan.

It works perfectly after I downgraded all the versions to 0.14. :heart:

**Comment by blumamir** [comment]
@sidharthv96  cool thanks for letting us know.
I'll add the supported version to the README, and we'll upgrade all plugins to v0.15.0 soon.

Please let us know if you observe any other issues or experience unclarity when using this repo :)

**Comment by sidharthv96** [comment]
Awesome!
Really blown away how easily everything works after the initial setup. 
I expected some manual work to connect express traces with kafka traces, but it worked out of the box with no extra configs.
Keep up the amazing work! 🚀

**Comment by blumamir** [comment]
Hi @sidharthv96 ,
I was trying to reproduce your issue but did not succeed in getting the error you are seeing.
Is it possible for you to share which plugin you were using and a minimal code snippet that reproduces it?

This is the code I run which did not throw the above error:
```js
import { NodeTracerProvider } from '@opentelemetry/node';
import { ConsoleSpanExporter, SimpleSpanProcessor } from '@opentelemetry/tracing';

const provider = new NodeTracerProvider({
    plugins: {
      kafkajs: {
        enabled: true,
        // You may use a package name or absolute path to the file.
        path: "opentelemetry-plugin-kafkajs",
      },
    },
  });

provider.addSpanProcessor(new SimpleSpanProcessor(new ConsoleSpanExporter()));

provider.register();

import {Kafka} from 'kafkajs';
const kafka = new Kafka({
    clientId: 'open-telemetry-demo',
    brokers: ['localhost:9092'],
});
const producer = kafka.producer();
producer.connect().then( async () => {
    console.log('connected');
    await producer.send({topic: 'test', messages: [{value: 'hello world'}]});
});

```

and my package.json:
```json
{
  "name": "otel-15-pg",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "start": "ts-node index.ts"
  },
  "devDependencies": {
    "typescript": "^4.1.3"
  },
  "dependencies": {
    "@opentelemetry/node": "^0.15.0",
    "@opentelemetry/tracing": "^0.15.0",
    "kafkajs": "^1.15.0",
    "opentelemetry-plugin-kafkajs": "^0.1.2",
    "ts-node": "^9.1.1"
  }
}
```

and the output to console:
```
{
  traceId: '7dc0842279ec38e9847e9100a575a4b1',
  parentId: undefined,
  name: 'test',
  id: '1c37102b70e53445',
  kind: 3,
  timestamp: 1611668057292756,
  duration: 58030,
  attributes: {
    'messaging.system': 'kafka',
    'messaging.destination': 'test',
    'messaging.destination_kind': 'topic'
  },
  status: { code: 1 },
  events: []
}
```

**Comment by sidharthv96** [comment]
I think we are missing something...

From these commits, the withSpan method has clearly been removed in [api](https://github.com/open-telemetry/opentelemetry-js/pull/1764/files#diff-dfc982f98a42e996ae5970988f328bd9a4f8f43647b26911d6db87d20656149c) and [tracing](https://github.com/open-telemetry/opentelemetry-js/pull/1764/files#diff-dfb7641af9a597066775219861be5ea44339ca6860d667b86fda245aac67848c) packages.

But it is used in the kafkajs plugin, so it should throw an error..
https://github.com/aspecto-io/opentelemetry-ext-js/blob/0711efbcdf64bfb0685020faa71c00fd66ea50f7/packages/plugin-kafkajs/src/kafkajs.ts#L102

**Comment by sidharthv96** [comment]
Got it @blumamir ! 
The withSpan part is only there in consumer tracer. So if you add a consumer to that topic, you should be able to replicate it.

**Comment by sidharthv96** [comment]
![image](https://user-images.githubusercontent.com/10703445/105854145-86a89000-600c-11eb-99c5-8ba374835e6c.png)
[Source](
https://github.com/open-telemetry/opentelemetry-js/pull/1764/files#diff-2da0e39d10c37384f3669b20cbc9158cf6406a3957b4bb445e369dc63b3def19)

The change seems straight forward and is referenced in their [upgrade guidelines.](https://github.com/open-telemetry/opentelemetry-js/blob/main/README.md#0140-to-0150)
![image](https://user-images.githubusercontent.com/10703445/105854664-2a923b80-600d-11eb-85b2-438d78c35f9e.png)

**Comment by blumamir** [comment]
Thanks, I managed to reproduce it with consumer 👍
