### ISSUE TITLE
amqplib: add support for ConfirmedChannel

### ISSUE THREAD

**Issue by blumamir** [aspecto-io/opentelemetry-ext-js#84]
[ConfirmedChannel](http://www.squaremobius.net/amqp.node/channel_api.html#confirmchannel) is currently not patched and not instrumented by the `amqplib` plugin.
We need to add support for that as well

**Comment by ssukienn** [comment]
This would be much appreciated. :)

**Comment by YanivD** [comment]
Hi @ssukienn,
Are you willing to submit a pull request with the necessary changes?

**Comment by jonaskello** [comment]
I just tried amqplib support out but whatever config I used I could not get any traces. Found this issue and now I understand why :-). Agree that it would be very nice to have this implemented.

**Comment by ssukienn** [comment]
Hi @YanivD,
Sorry for the delay. As for now, I am quite busy but I might give it a try later on. Can't be more specific and I wouldn't rely on myself for this one so if someone would like to contribute, please do.

Do you or ur team have some ideas or comments/considerations regarding potential implementation for CChannels here? I am quite new to open telemetry all together but was checking out this repository a little and I pretty much understand the concept.

**Comment by blumamir** [comment]
Hi @ssukienn ,
The implementation for Confirmed Channel should be very similar to the implementation of regular channels. It involves examining the source code of amqplib and understanding which functions to patch, when to start and end the span, and which attributes to add to it. 
If you want to take this task, I can help you with setup and mentoring, via zoom and\or discussion in this issue.

**Comment by ssukienn** [comment]
Hi @blumamir,
I played a bit with it. Have an idea of how to implement it. How would you like to treat a confirm? From my understanding of spec, it should be a separate span of server kind and receive operation (might be mistaken though). But what about the duration of it? 

1) Should it last from send operation in ambqlib till confirm and callback completion or timeout (confirm may never come)
* send->broker->confirm->callback
* send->timeout
Example:
![image](https://user-images.githubusercontent.com/16635781/125208697-6441c080-e294-11eb-9447-4b41fae956b8.png)
I am not sure that spans should cover roundtrip area and this span in fact is covering the time of msg getting to the broker and broker's confirms arriving to service or timeout if nothing arrives

2) Should it last from a real confirm time so pretty much time of instrumentation + callback itself.  
* confirm->callback 
In this case still probably some reference would be required to store on local state (channel) to keep a reference to already finished send span in order to create confirm span as it's child. Due to reference keeping which would consist of msg buffer for comparison, timeout to clear it would be required similar like with consume. So we are facing a scenario where timeout might clear the reference but confirm arrived later so we cannot create confirm span with correct parent. Should we create it as a sibling of send context or we should skip instrumentation in such situation (you will never see confirm span but might see consume later on)?

I like the 2) option (not sure it is correct), but it has some caveats.

**Comment by blumamir** [comment]
Thanks for doing the research.
From what I know, the "receive" span is meant to be used for the other part of the queue which is consuming the messages. 
I was thinking that in the case of ConfirmedChannel, we should end the "publish" span when the confirm callback is called, and set error\success on it according to the confirm result.

> From my understanding of spec, it should be a separate span of server kind and receive operation (might be mistaken though)

Can you share the relevant part from the spec?

**Comment by ssukienn** [comment]
Thanks for response,

> Span kind
>A producer of a message should set the span kind to PRODUCER unless it synchronously waits for a response: then it should use >CLIENT. The processor of the message should set the kind to CONSUMER unless it always sends back a reply that is directed to >the producer of the message (as opposed to e.g., a queue on which the producer happens to listen): then it should use SERVER.
Not sure we can treat "reply" as confirm in that sense. Probably the intent was for the form of RPCs with conversationId/replyQueue  etc. but I assumed that broker is a SERVER here.

>Operation name | Description
>send | A message is sent to a destination by a message producer/client.
>receive | A message is received from a destination by a message consumer/server.
>process | A message that was previously received from a destination is processed by a message consumer/server.
Okay, I missed the "is received from a destination" in receive. In our case it is actually a publisher who receives confirms from a broker and the message already might be consumed, for sure is taken care of by the broker. 

So looking closer I think spec is really silent about this case. Maybe taking this issue to opentelemtry for insights would be way to go.

>I was thinking that in the case of ConfirmedChannel, we should end the "publish" span when the confirm callback is called, and >set error\success on it according to the confirm result.
Okay, so pretty much scenario 1) but you want to merge send span with above "confirm" span. 
Is it fine though that then send span with CC channel might end later than potential consume span. And assuming confirm will never arrive span will end at timeout hit and will be errored but actual send might be handled properly by the broker. Is it fine?

**Comment by blumamir** [comment]
> Not sure we can treat "reply" as confirm in that sense. Probably the intent was for the form of RPCs with conversationId/replyQueue etc. but I assumed that broker is a SERVER here.

> So looking closer I think spec is really silent about this case. Maybe taking this issue to opentelemtry for insights would be way to go.


I too think that the intent was for the logical messages being sent to the messaging system, and not for implementation/protocol messages. We can take it to the community and open an issue in the specification repo if you like, but I am also fine with implementing it as a kind `CONSUMER` and ending the span when we get an ack that the publish is done (either confirmed or errored) if you feel comfortable with it.

> Is it fine though that then send span with CC channel might end later than potential consume span.

In my opinion, yes. In a distributed system, all combinations of operation timing should be allowed and expected. The publisher can get the acknowledgment that the message was received by the broker at any time, regardless of the consumer.

> And assuming confirm will never arrive span will end at timeout hit and will be errored but actual send might be handled properly by the broker. Is it fine? And if confirm actually arrives after timeout (late confirm) should we skip it or do some "synthetic" span. We would not have parentSpan reference (cleared at timeout).

We can set timeout on the publish span and be prepared for a situation where the confirm never arrives. The amqplib library itself does not setup any timeout for confirm to arrive, it is storing each message in an `unconfirmed` array, which will not be cleared until the confirm message is received from the broker. Thus I think it is safe for the instrumentation to mimic this behavior as well and wait for the confirm to arrive (for the callback to be called) without timeouts.

To my understanding from the code, except for socket disconnection, there are no valid use cases in which the server will not eventually reply with confirm to the publisher. Such cases will cause a memory leak in amqplib itself.

When consuming a message, this assumption does not hold, since the entity which is responsible for acking is the user code, which can be written in a way that will never response back to the broker.

**Comment by ssukienn** [comment]
>[...] but I am also fine with implementing it as a kind CONSUMER and ending the span when we get an ack that the publish is done (either confirmed or errored) if you feel comfortable with it.

So we would end with 2 consumer spans? I would stick to publisher kind or separating it to 2 spans: immediate send like now, and consumer confirm which would end on confirm callback. 

>To my understanding from the code, except for socket disconnection, there are no valid use cases in which the server will not eventually reply with confirm to the publisher. Such cases will cause a memory leak in amqplib itself.

I am afraid that without timeout the buffers which would need to be stored on the channel ref array (to find span related to the content of the messages) might take a considerate amount of memory assuming hanging confirms. On the other hand, the unconfirmed callbacks in amqlib might do the same. Not entirely sure if a scenario where confirmation won't arrive with an alive connection is possible. Probably not as it is TCP so you might be right. Then I will proceed without timeouts. 

Lastly, not related to the issue, but I think setting the error when publish returns false is incorrect. As it doesn't mean that you need to resend according to: https://github.com/squaremo/amqp.node/issues/636. You should just halt further sends until drain. I always thought this is the case but apparently not. 

Thanks for the inputs. I will go from there and will open PR in some time. Probably somewhere near the end of the month or next as I will be off.

**Comment by blumamir** [comment]
> > [...] but I am also fine with implementing it as a kind CONSUMER and ending the span when we get an ack that the publish is done (either confirmed or errored) if you feel comfortable with it.
> 
> So we would end with 2 consumer spans? I would stick to publisher kind or separating it to 2 spans: immediate send like now, and consumer confirm which would end on confirm callback.

Sorry I meant to write PRODUCER. you are right, we should have a single publish span which will end upon confirm indication.

> which would need to be stored on the channel ref array (to find span related to the content of the messages)

You can also avoid the ref array and use a closure param to the patched callback (let me know if it's not clear enough).



> Lastly, not related to the issue, but I think setting the error when publish returns false is incorrect

Agree. I think we need to set the publish span to error only when the confirm callback is called with an error (indicating that there is not confirmation on the message being sent successfully).


> Thanks for the inputs. I will go from there and will open PR in some time. Probably somewhere near the end of the month or next as I will be off.

Great, thank you!

**Comment by ssukienn** [comment]
Hi, soon I will have time to get back to this.

@blumamir With closure you meant to create span in cc publish patch and close over it with confirm callback function and then in normal publish patch do nothing when CC? (CC publish is calling normal publish but we know if we use CC or C). This is ok if starting span before calling actual normal publish is acceptable.

Until now I was always creating span (saving ref) in normal publish patch (with ending right away in case of C - as in current implementation) and in case of CC ending inside patched callback based on ref saved on channel object.

Or do you really want to somehow still create it in normal publish patch and use it as closure param in the callback of CC publish which I don't really see how you would like to transport it up :) 

Thanks in advance for the clarification!

**Comment by blumamir** [comment]
> meant to create span in cc publish patch and close over it with confirm callback function and then in normal publish patch do nothing when CC

This is what I meant yes, but sounds like you are very much into the details and there might be things that I am not aware of. 
If you have a working solution that needs polishing, might be easier to have the discussion with a code reference in a relevant PR when you find the time for it
