### ISSUE TITLE
Context propagation between producer and consumer doesn't work.

### ISSUE THREAD

**Issue by IvanovOleg** [aspecto-io/opentelemetry-ext-js#88]
Hello,
I've created two simple apps: producer and consumer and enabled autoinstrumentation. I am getting spans from those apps in Jaeger, but they are not connected. I added the debug logging to console and see that on the producer side opentelemetry-instrumentation doesn't add any headers. Is there any specific step required to enable context propagation?
Thanks

**Comment by blumamir** [comment]
Hi @IvanovOleg ,
Thanks for opening the issue.
What instrumentation library are you using?
aws-sdk, kafkajs or amqplib?

Can you share more of your setup?

**Comment by IvanovOleg** [comment]
@blumamir kafkajs

**Comment by blumamir** [comment]
Can you please paste here your package.json dependencies? specifically `@opentelemetry/api` and `opentelemetry-instrumentation-kafkajs`

Are you configuring any special propagators in opentelemetry? or using the default propagators that are shipped with `NodeTracerProvider`?

**Comment by IvanovOleg** [comment]
producer:
``` JSON
{
  "name": "producer",
  "version": "0.1.0",
  "description": "A simple kafka producer.",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/IvanovOleg/nodejs-otel-sample.git"
  },
  "keywords": [
    "opentelemetry"
  ],
  "author": "Oleg Ivanov",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/IvanovOleg/nodejs-otel-sample/issues"
  },
  "homepage": "https://github.com/IvanovOleg/nodejs-otel-sample#readme",
  "dependencies": {
    "@opentelemetry/api": "^1.0.0-rc.0",
    "@opentelemetry/exporter-collector": "^0.18.0",
    "@opentelemetry/instrumentation": "^0.18.0",
    "@opentelemetry/node": "^0.18.0",
    "@opentelemetry/tracing": "^0.18.0",
    "kafkajs": "^1.15.0",
    "log4js": "^6.3.0",
    "opentelemetry-instrumentation-kafkajs": "^0.2.3"
  }
}
```
consumer:
``` JSON
{
  "name": "consumer",
  "version": "0.1.0",
  "description": "A simple kafka consumer app.",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/IvanovOleg/nodejs-otel-sample.git"
  },
  "keywords": [
    "opentelemetry"
  ],
  "author": "Oleg Ivanov",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/IvanovOleg/nodejs-otel-sample/issues"
  },
  "homepage": "https://github.com/IvanovOleg/nodejs-otel-sample#readme",
  "dependencies": {
    "@opentelemetry/api": "^1.0.0-rc.0",
    "@opentelemetry/exporter-collector": "^0.18.0",
    "@opentelemetry/instrumentation": "^0.18.0",
    "@opentelemetry/node": "^0.18.0",
    "@opentelemetry/tracing": "^0.18.0",
    "kafkajs": "^1.15.0",
    "log4js": "^6.3.0",
    "opentelemetry-instrumentation-kafkajs": "^0.3.0"
  }
}

```

**Comment by blumamir** [comment]
I'm not sure about this case, but there have been cases of incompatibility with the `@opentelemetry/api` versions between the plugin and the provider.

The instrumentation library depends on `"@opentelemetry/api": "^0.18.0"`, which grabs a different version than the one used by the provider.
I'm hoping to get to testing it soon. In the meantime, you can try to change the dependency in your application to `"@opentelemetry/api": "^0.18.0"`. It might be a temporary workaround until we release a version compatible with the new api major version.

**Comment by IvanovOleg** [comment]
@blumamir Will try. Thanks

**Comment by IvanovOleg** [comment]
@blumamir I tried "@opentelemetry/api": "^0.18.0" and it doesn't work either.

**Comment by blumamir** [comment]
Cool thanks for letting us know.
I'll need to dive deeper into this issue, probably one day next week.
I Will update here on the progress.

Please share if you find other issues with the plugin functionality/documentation

**Comment by blumamir** [comment]
@IvanovOleg , I took a second look on your setup. your producer is using `"opentelemetry-instrumentation-kafkajs": "^0.2.3"`, which is compatible with version v0.17.0 of opentelemetry.
You should upgrade to `"opentelemetry-instrumentation-kafkajs": "^0.3.0"` which is compatible with opentelemetry v0.18.0.

Until opentelemetry apis stabilize, we need to publish a separate version of instrumentation which are compatible with each breaking change in the core packages.

**Comment by IvanovOleg** [comment]
@blumamir Yes, that 0.3.0 fixes the issue
