### ISSUE TITLE
Upstreaming instrumentations

### ISSUE THREAD

**Issue by seemk** [aspecto-io/opentelemetry-ext-js#93]
Hey, great work on the instrumentations!

Do you have plans to upstream these to `opentelemetry-js-contrib` in the nearer future?

**Comment by blumamir** [comment]
Hi, @seemk 
By maintaining these instrumentations in a separate repo we are able to add features and bug fixes super fast, and publish new versions frequently. It also allows us to stay up to date with the latest otel sdk versions.
All the PRs in this repo are unit-tested, reviewed and verified with RC versions on our setup before publishing.
The instrumentations are vendor-neutral, strictly follows the open telemetry semantic conventions, and released with an open-source license.

We welcome any contribution, so if you find an issue or need a feature, feel free to reach out or open a PR and we'll review it

**Comment by iNikem** [comment]
@blumamir Even if this code lives in opentelemetry-js-contrib repo you may be codeowners for it and thus move with whatever speed you desire. And that certainly will help with discoverability of this instrumentation, don't you think?

**Comment by blumamir** [comment]
> you may be codeowners for it and thus move with whatever speed you desire

As far as I know, approving PRs in contrib repo requires 3 approvers, 2 of them have to be maintainers. This process can sometimes last months from my experience.
Is there any documentation regarding code owners policy in contrib?

**Comment by iNikem** [comment]
I will raise this question during next Otel maintainers meetings. What you describe goes against the very idea of contrib repo and must be addressed by OpenTelemetry.

**Comment by dyladan** [comment]
@blumamir There is no documentation for contrib, you are referring to the guidelines from the core repo. In contrib, we typically have been merging with 2 reviews, only 1 of which is a maintainer.

During the maintainer meeting this week we talked about ways to close this gap. One of the ideas we considered is making the contrib maintainership a separate role from the core maintainership. Since you obviously have put a ton of time into instrumentations, would you consider taking a maintainership role for the contrib/instrumentations if it was created?

**Comment by blumamir** [comment]
Thanks @dyladan 
If this role is created, I'll be glad to apply for it and to help maintain the contrib instrumentations

**Comment by dyladan** [comment]
@blumamir there isn't such a role but for now making you an approver on the repo would be a good first step while it is discussed. I know other SIGs are considering making similar changes. Are you a member of the opentelemetry org (prerequisite for any official position)? If not, I'm happy to be one of your sponsors for membership.

**Comment by blumamir** [comment]
> Are you a member of the opentelemetry org (prerequisite for any official position)? If not, I'm happy to be one of your sponsors for membership.

Not yet, thank you for offering :) Looks like I need another sponsor to become opentelemetry org member. Is anyone else in this conversation willing to sponsor me for membership?

**Comment by owais** [comment]
@blumamir I'd be more than happy to. Can you please open a PR like this one: https://github.com/open-telemetry/community/issues/711

**Comment by blumamir** [comment]
> @blumamir I'd be more than happy to. Can you please open a PR like this one: [open-telemetry/community#711](https://github.com/open-telemetry/community/issues/711)

Done
https://github.com/open-telemetry/community/issues/714

thanks

**Comment by pauldraper** [comment]
+1 These are really great quality. But some sort of discovery (even if a link) would make these more used.

**Comment by blumamir** [comment]
> +1 These are really great quality. But some sort of discovery (even if a link) would make these more used.

Thanks. Where would you expect such a link?

**Comment by pauldraper** [comment]
Well...opentelemetry/opentelemetry-js is where I start when it comes to JS-related Otel stuff...

**Comment by blumamir** [comment]
Opentelemetry-js is the official repo from otel organization, where this one is a third-party contributions.
But we did add all the instrumentation libraries to the [opentelemetry registry](https://opentelemetry.io/registry/), and open for suggestions on how to make them more discoverable.

How did you end up finding this repo?

**Comment by pauldraper** [comment]
https://github.com/open-telemetry/opentelemetry-js-contrib/issues/323#issuecomment-769452494
